apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: alpha
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: beta
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
